removing taglib because it giving error on Ubuntu while importing essentia in python
import essentia.standard
Traceback (most recent call last):
File "", line 1, in 
File "/home/ubuntu/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/essentia/init.py", line 1, in 
import _essentia
ImportError: /home/ubuntu/.linuxbrew/lib/libessentia.so: undefined symbol: _ZNK6TagLib6String6to8BitB5cxx11Eb